# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: src/**

  # release:
  #   types: []
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pull-requests: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g documentation

      - run: echo "DOCPATH=${GITHUB_REF:10}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      - run: echo "DOCPATH=head" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/') != true

      - run: echo "docs/$DOCPATH"
        
      - run: >-
          documentation build src/** -c docs/docs.yml
          --project-name Censor
          --project-version $DOCPATH
          --project-homepage "https://github.com/thatrandomperson5/censorjs"
          --project-description "A javascript event/function interception library." 
          -f html --github -o docs/$DOCPATH

      - run: sed -i -E 's/[\x22\x27](assets\/.[^\x22\x27]+)[\x22\x27]/\"..\/\1\"/g' "docs/$DOCPATH/index.html"
      - run: rm -rf docs/assets &>/dev/null
      - run: mv docs/$DOCPATH/assets docs/assets
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update Documentation
