name: Release versions
on: 
  workflow_dispatch:
  
jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build with Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cp src/censor.js release/censor.module.js
      - run: echo "export {censor, CensorObject}" >> release/censor.module.js

      - run: cp src/injection-tooling.js release/injection-tooling.module.js
      - run: echo "export {censorResource, softRefresh}" >> release/injection-tooling.module.js
      
      - run: npm i minify -g
      - run: minify src/censor.js > release/censor.min.js
      - run: minify release/censor.module.js > release/censor.module.min.js

      - run: minify src/injection-tooling.js > release/injection-tooling.min.js
      - run: minify release/injection-tooling.module.js > release/injection-tooling.module.min.js
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
      
